apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
type: Opaque
stringData:
  REDIS_HOST: {{ .Release.Name }}-redis-db-service
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password }}