webServer:
  name: web-server
  replicaCount: 1
  configMapName: web-server-dev-config
  image:
    repository: webfrontend
    tag: latest
    pullPolicy: Never
  resources:
    limits:
      memory: "200Mi"
      cpu: "200m"
  containerPort: 80
  service:
    port: 80
    targetPort: 3000
    type: ClusterIP