replicaCount: 1

image:
  repository: modelbackend
  tag: latest
  pullPolicy: Never

resources:
  limits:
    memory: "1Gi"
    cpu: "200m"

service:
  port: 8000
  targetPort: 8000
  type: ClusterIP

redis:
  secretName: redis-server-release-dev-redis-secret